const router = require("express").Router();
const { protect } = require("../middleware/authMiddleware");
const { catchUpRecurring } = require("../middleware/recurringMiddleware");
const controller = require("../controllers/expenseController");
const transactions = require("../controllers/transactionController");
router.use(protect, catchUpRecurring);
router.post("/add", controller.addExpense);
router.get("/get", controller.getAllExpense);
router.get("/downloadexcel", controller.downloadExpenseExcel);
router.put("/:id", transactions.update("expense"));
router.delete("/:id", controller.deleteExpense);
module.exports = router;
