const router = require("express").Router();
const { protect } = require("../middleware/authMiddleware");
const { catchUpRecurring } = require("../middleware/recurringMiddleware");
const transactions = require("../controllers/transactionController");
const budgets = require("../controllers/budgetController");
const goals = require("../controllers/goalController");
const recurring = require("../controllers/recurringController");
router.use(protect, catchUpRecurring);
router.get("/transactions", transactions.list);
router.get("/transactions/categories", transactions.categories);
router.get("/transactions/export", transactions.exportData());
router.get("/budgets", budgets.list);
router.post("/budgets", budgets.add);
router.put("/budgets/:id", budgets.update);
router.delete("/budgets/:id", budgets.remove);
router.get("/goals", goals.list);
router.post("/goals", goals.add);
router.put("/goals/:id", goals.update);
router.post("/goals/:id/contributions", goals.contribute);
router.delete("/goals/:id", goals.remove);
router.get("/recurring", recurring.list);
router.post("/recurring", recurring.add);
router.patch("/recurring/:id", recurring.update);
router.delete("/recurring/:id", recurring.remove);
module.exports = router;
