const router = require("express").Router();
const { protect } = require("../middleware/authMiddleware");
const { catchUpRecurring } = require("../middleware/recurringMiddleware");
const controller = require("../controllers/incomeController");
const transactions = require("../controllers/transactionController");
router.use(protect, catchUpRecurring);
router.post("/add", controller.addIncome);
router.get("/get", controller.getAllIncome);
router.get("/downloadexcel", controller.downloadIncomeExcel);
router.put("/:id", transactions.update("income"));
router.delete("/:id", controller.deleteIncome);
module.exports = router;
